=== icplayer/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

    <xs:element name="addon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="model">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PropertyType">
        <xs:sequence>
            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="nameLabel" type="xs:string"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="isLocalized">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

</xs:schema>

=== icplayer/icplayer/addons/Quiz/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Quiz' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="Questions" nameLabel="Quiz_property_Questions" type="list" isDefault="true">
            <property name="Question" nameLabel="Quiz_property_Question" type="html" isLocalized="true"/>
            <property name="CorrectAnswer" nameLabel="Quiz_property_CorrectAnswer" type="string"/>
            <property name="WrongAnswer1" nameLabel="Quiz_property_WrongAnswer1" type="string"/>
            <property name="WrongAnswer2" nameLabel="Quiz_property_WrongAnswer2" type="string"/>
            <property name="WrongAnswer3" nameLabel="Quiz_property_WrongAnswer3" type="string"/>
            <property name="Hint" nameLabel="Quiz_property_hint" type="html" isLocalized="true"/>
        </property>
        <property name="TestMode" nameLabel="Quiz_property_TestMode" type="boolean"/>
        <property name="ShowHelpButtons" nameLabel="Quiz_property_ShowHelpButtons" type="boolean"/>
        <property name="NextAfterSelect" nameLabel="Quiz_property_NextAfterSelect" type="boolean"/>
        <property name="NextLabel" nameLabel="Quiz_property_NextLabel" type="string" isLocalized="true"/>
        <property name="GameLostMessage" nameLabel="Quiz_property_GameLostMessage" type="html" isLocalized="true"/>
        <property name="GameWonMessage" nameLabel="Quiz_property_GameWonMessage" type="html" isLocalized="true"/>
        <property name="ShowSummary" nameLabel="Quiz_property_Summary" type="boolean"/>
        <property name="GameSummaryMessage" nameLabel="Quiz_property_GameSummaryMessage" type="html" isLocalized="true"/>
        <property name="CorrectGameMessage" nameLabel="Quiz_property_CorrectGameMessage" type="html" isLocalized="true"/>
        <property name="WrongGameMessage" nameLabel="Quiz_property_WrongGameMessage" type="html" isLocalized="true"/>
        <property name="Center vertically" nameLabel="Quiz_property_center_vertically" type="boolean"/>
        <property name="isActivity" nameLabel="Quiz_property_isActivity" type="boolean"/>
        <property name="langAttribute" displayName="Lang attribute" nameLabel="Quiz_property_lang_attribute" type="string" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="Quiz_property_speech_texts" type="staticlist">
            <property name="Question" nameLabel="Quiz_speech_text_question" type="staticrow">
                <property name="Question" nameLabel="Quiz_speech_text_question" type="string"/>
            </property>
            <property name="Answer" nameLabel="Quiz_speech_text_answer" type="staticrow">
                <property name="Answer" nameLabel="Quiz_speech_text_answer" type="string"/>
            </property>
            <property name="FiftyFiftyButton" nameLabel="Quiz_speech_text_fifty_fifty_button" type="staticrow">
                <property name="FiftyFiftyButton" nameLabel="Quiz_speech_text_fifty_fifty_button" type="string"/>
            </property>
            <property name="FiftyFiftyButtonWhenNotEnoughAnswers" nameLabel="Quiz_speech_text_fifty_fifty_button_when_not_enough_answers" type="staticrow">
                <property name="FiftyFiftyButtonWhenNotEnoughAnswers" nameLabel="Quiz_speech_text_fifty_fifty_button_when_not_enough_answers" type="string"/>
            </property>
            <property name="HintButton" nameLabel="Quiz_speech_text_hint_button" type="staticrow">
                <property name="HintButton" nameLabel="Quiz_speech_text_hint_button" type="string"/>
            </property>
            <property name="CommentField" nameLabel="Quiz_speech_text_comment_field" type="staticrow">
                <property name="CommentField" nameLabel="Quiz_speech_text_comment_field" type="string"/>
            </property>
            <property name="Hint" nameLabel="Quiz_speech_text_hint" type="staticrow">
                <property name="Hint" nameLabel="Quiz_speech_text_hint" type="string"/>
            </property>
            <property name="Summary" nameLabel="Quiz_speech_text_summary" type="staticrow">
                <property name="Summary" nameLabel="Quiz_speech_text_summary" type="string"/>
            </property>
            <property name="Selected" nameLabel="Quiz_speech_text_selected" type="staticrow">
                <property name="Selected" nameLabel="Quiz_speech_text_selected" type="string"/>
            </property>
            <property name="Correct" nameLabel="Quiz_speech_text_correct" type="staticrow">
                <property name="Correct" nameLabel="Quiz_speech_text_correct" type="string"/>
            </property>
            <property name="Wrong" nameLabel="Quiz_speech_text_wrong" type="staticrow">
                <property name="Wrong" nameLabel="Quiz_speech_text_wrong" type="string"/>
            </property>
            <property name="Inactive" nameLabel="Quiz_speech_text_inactive" type="staticrow">
                <property name="Inactive" nameLabel="Quiz_speech_text_inactive" type="string"/>
            </property>
            <property name="OutOf" nameLabel="Quiz_speech_text_out_of" type="staticrow">
                <property name="OutOf" nameLabel="Quiz_speech_text_out_of" type="string"/>
            </property>
        </property>
    </model>
</addon>

=== icplayer/icplayer/addons/Image_Identification/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Image_Identification' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Image' nameLabel="Image_Identification_property_image" type='image' isDefault='true' />
		<property name="SelectionCorrect" nameLabel="Image_Identification_property_selection_correct" type="boolean" />
		<property name="Is Disabled" nameLabel="Image_Identification_property_is_disabled" type="boolean" />
		<property name="Is not an activity" nameLabel="Image_Identification_property_is_not_an_activity" type="boolean" />
		<property name="Block in error checking mode" nameLabel="Image_Identification_property_block_in_error_checking_mode" type="boolean" />
        <property name="blockWrongAnswers" displayName="Block wrong answers" nameLabel="Image_Identification_property_block_wrong_answers" type="boolean" />
		<property name="Alt text" nameLabel="Image_Identification_property_alt_text" type="string" isLocalized="true" />
		<property name="langAttribute" displayName="Lang attribute" nameLabel="Image_Identification_property_lang_attribute" type="string" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="Image_Identification_property_speech_texts" type="staticlist">

            <property name="Selected" nameLabel="Image_Identification_selected" type="staticrow">
                <property name="Selected" nameLabel="Image_Identification_selected" type="string"/>
            </property>

            <property name="Deselected" nameLabel="Image_Identification_deselected" type="staticrow">
                <property name="Deselected" nameLabel="Image_Identification_deselected" type="string"/>
            </property>

            <property name="Correct" nameLabel="Image_Identification_correct" type="staticrow">
                <property name="Correct" nameLabel="Image_Identification_correct" type="string"/>
            </property>

            <property name="Wrong" nameLabel="Image_Identification_wrong" type="staticrow">
                <property name="Wrong" nameLabel="Image_Identification_wrong" type="string"/>
            </property>

        </property>
	</model>
</addon>

=== icplayer/icplayer/addons/gamememo/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='gamememo' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Pairs' nameLabel="gamememo_property_pairs" type='list'>
			<property name="A (text)" nameLabel="gamememo_property_pair_a_text" type="string" isLocalized="true" />
			<property name="A (image)" nameLabel="gamememo_property_pair_a_image" type="image" />
			<property name="A (alt text)" nameLabel="gamememo_property_alt_text_style_a" type="string" />
			<property name="B (text)" nameLabel="gamememo_property_pair_b_text" type="string" isLocalized="true" />
			<property name="B (image)" nameLabel="gamememo_property_pair_b_image" type="image" />
			<property name="B (alt text)" nameLabel="gamememo_property_alt_text_style_a" type="string" />
		</property>
		<property name="Columns" nameLabel="gamememo_property_columns" type="string" />
		<property name="Rows" nameLabel="gamememo_property_rows" type="string" />
		<property name="Use two styles for cards" nameLabel="gamememo_property_use_two_styles_for_cards" type="boolean" />
		<property name="Image for style A" nameLabel="gamememo_property_image_for_style_a" type="image" />
		<property name="Image for style B" nameLabel="gamememo_property_image_for_style_b" type="image" />
		<property name="Style A cover alt text" nameLabel="gamememo_property_alt_text_style_a" type="string" />
		<property name="Style B cover alt text" nameLabel="gamememo_property_alt_text_style_b" type="string" />
		<property name="Keep cards aspect ratio" nameLabel="gamememo_property_keep_cards_aspect_ratio" type="boolean" />
		<property name="Show cards for preview" nameLabel="gamememo_property_show_cards_for_preview" type="boolean" />
        <property name="Is Not Activity" nameLabel="gamememo_property_is_not_activity" type="boolean" />
        <property name="Image Mode" nameLabel="gamememo_property_image_mode" type="{Original, Stretch, KeepAspect}"/>
        <property name="Keep wrong marking" nameLabel="gamememo_property_keep_wrong_marking" type="boolean" />
        <property name="Time to solve" nameLabel="gamememo_property_time_to_solve" type="string" />
        <property name="Session ended message" nameLabel="gamememo_property_session_ended_message" type="html" />
		<property name="Click to turn over incorrect pair" nameLabel="gamememo_property_click_to_turn_over_incorrect_pair" type="boolean" />
		<property name="langAttribute" displayName="Lang attribute" nameLabel="Connection_property_lang_attribute" type="string" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="Connection_property_speech_texts" type="staticlist">

            <property name="Revealed" nameLabel="gamememo_revealed" type="staticrow">
                <property name="Revealed" nameLabel="gamememo_revealed" type="string"/>
            </property>

			<property name="Paired" nameLabel="gamememo_paired" type="staticrow">
                <property name="Paired" nameLabel="gamememo_paired" type="string"/>
            </property>

			<property name="Value" nameLabel="gamememo_value_of" type="staticrow">
                <property name="Value" nameLabel="gamememo_value_of" type="string"/>
            </property>

			<property name="WrongColor" nameLabel="gamememo_wrong_color" type="staticrow">
                <property name="WrongColor" nameLabel="gamememo_wrong_color" type="string"/>
            </property>

			<property name="Match" nameLabel="gamememo_match" type="staticrow">
                <property name="Match" nameLabel="gamememo_match" type="string"/>
            </property>

			<property name="NotMatch" nameLabel="gamememo_not_match" type="staticrow">
                <property name="NotMatch" nameLabel="gamememo_not_match" type="string"/>
            </property>

			<property name="CurrentlySelected" nameLabel="gamememo_currently_selected" type="staticrow">
                <property name="CurrentlySelected" nameLabel="gamememo_currently_selected" type="string"/>
            </property>

			<property name="TurnOver" nameLabel="gamememo_turn_over" type="staticrow">
                <property name="TurnOver" nameLabel="gamememo_turn_over" type="string"/>
            </property>

			<property name="OutOf" nameLabel="gamememo_out_of" type="staticrow">
                <property name="OutOf" nameLabel="gamememo_out_of" type="string"/>
            </property>

			<property name="Found" nameLabel="gamememo_found" type="staticrow">
                <property name="Found" nameLabel="gamememo_found" type="string"/>
            </property>

			<property name="RevealedCards" nameLabel="gamememo_revealed_cards" type="staticrow">
                <property name="RevealedCards" nameLabel="gamememo_revealed_cards" type="string"/>
            </property>

		</property>
	</model>
</addon>

=== icplayer/icplayer/addons/Slideshow/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Slideshow' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Audio' nameLabel="Slideshow_property_audio" type='list'>
			<property name="MP3" nameLabel="Slideshow_property_mp3" type="audio" />
			<property name="OGG" nameLabel="Slideshow_property_ogg" type="audio" />
		</property>
		<property name="Slides" nameLabel="Slideshow_property_slides" type="list">
			<property name="Image" nameLabel="Slideshow_property_image" type="image" />
			<property name="Start" nameLabel="Slideshow_property_start" type="string" />
		</property>
		<property name="Texts" nameLabel="Slideshow_property_texts" type="list">
			<property name="Text" nameLabel="Slideshow_property_text" type="string" isLocalized="true" />
			<property name="Top" nameLabel="Slideshow_property_top" type="string" />
			<property name="Left" nameLabel="Slideshow_property_left" type="string" />
			<property name="Start" nameLabel="Slideshow_property_start" type="string" />
			<property name="End" nameLabel="Slideshow_property_end" type="string" />
		</property>
		<property name="No audio" nameLabel="Slideshow_property_no_audio" type="boolean" />
		<property name="Presentation duration" nameLabel="Slideshow_property_presentation_duration" type="string" />
		<property name="Slide animation" nameLabel="Slideshow_property_slide_animation" type="boolean" />
		<property name="Text animation" nameLabel="Slideshow_property_text_animation" type="boolean" />
		<property name="Hide progressbar" nameLabel="Slideshow_property_hide_progressbar" type="boolean" />
		<property name="Show slide" nameLabel="Slideshow_property_show_slide" type="string" />
		<property name="Group next and previous buttons" nameLabel="Slideshow_property_group_next_and_previous_buttons" type="boolean" />
		<property name="Narration" nameLabel="Slideshow_property_narration" type="narration" />
	</model>
</addon>

=== icplayer/icplayer/addons/Image_Viewer_Public/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Image_Viewer_Public' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Image' nameLabel="Image_Viewer_Public_property_image" type='image' />
		<property name="Frames" nameLabel="Image_Viewer_Public_property_frames" type="string" />
		<property name="Frame size" nameLabel="Image_Viewer_Public_property_frame_size" type="{Original, Keep aspect ratio, Stretch}" />
		<property name="Sounds" nameLabel="Image_Viewer_Public_property_sounds" type="list">
			<property name="MP3 sound" nameLabel="Image_Viewer_Public_property_mp3_sound" type="audio" />
			<property name="OGG sound" nameLabel="Image_Viewer_Public_property_ogg_sound" type="audio" />
			<property name="AAC sound" nameLabel="Image_Viewer_Public_property_aac_sound" type="audio" />
		</property>
		<property name="Frame names" nameLabel="Image_Viewer_Public_property_frame_names" type="list">
			<property name="name" nameLabel="Image_Viewer_Public_property_name" type="string" />
			<property name="frame" nameLabel="Image_Viewer_Public_property_frames" type="string" />
		</property>
		<property name="Alternative texts" nameLabel="Image_Viewer_Public_property_alternative_texts" type="list">
			<property name="Alternative text" nameLabel="Image_Viewer_Public_property_alternative_text" type="text" />
			<property name="frame" nameLabel="Image_Viewer_Public_property_frames" type="string" />
		</property>
		<property name="isClickDisabled" nameLabel="Image_Viewer_Public_property_is_click_disabled" type="boolean" />
		<property name="Labels" nameLabel="Image_Viewer_Public_property_labels" type="list">
			<property name="Text" nameLabel="Image_Viewer_Public_property_text" type="string" isLocalized="true" />
			<property name="Top" nameLabel="Image_Viewer_Public_property_top" type="string" />
			<property name="Left" nameLabel="Image_Viewer_Public_property_left" type="string" />
			<property name="Frames" nameLabel="Image_Viewer_Public_property_frames" type="string" />
		</property>
		<property name="Show watermark" nameLabel="Image_Viewer_Public_property_show_watermark" type="boolean" />
		<property name="Watermark color" nameLabel="Image_Viewer_Public_property_watermark_color" type="string" />
		<property name="Watermark opacity" nameLabel="Image_Viewer_Public_property_watermark_opacity" type="string" />
		<property name="Watermark size" nameLabel="Image_Viewer_Public_property_watermark_size" type="string" />
		<property name="Show frame" nameLabel="Image_Viewer_Public_property_show_frame" type="string" />
		<property name="Animation" nameLabel="Image_Viewer_Public_property_animation" type="{None, Linear, Fading}" />
		<property name="Correct frames" nameLabel="Image_Viewer_Public_property_correct_frames" type="string" />
		<property name="Do not reset" nameLabel="Image_Viewer_Public_property_do_not_reset" type="boolean" />
		<property name="Random frame" nameLabel="Image_Viewer_Public_property_random_frame" type="boolean" />
		<property name="Initial frame" nameLabel="Image_Viewer_Public_property_initial_frame" type="string" />
		<property name="Show frame counter" nameLabel="Image_Viewer_Public_property_show_frame_counter" type="boolean" />
		<property name="langAttribute"  nameLabel="Image_Viewer_Public_property_lang_attribute" type="string" />
	</model>
</addon>

=== icplayer/icplayer/addons/WritingCalculations/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='WritingCalculations' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name='Value' nameLabel="WritingCalculations_property_value" type='text' isDefault="true"/>
        <property name='Signs' nameLabel="WritingCalculations_property_signs" type='list'>
            <property name='Addition' nameLabel="WritingCalculations_property_addition" type='string' />
            <property name='Subtraction' nameLabel="WritingCalculations_property_subtraction" type='string' />
            <property name='Division' nameLabel="WritingCalculations_property_division" type='string' />
            <property name='Multiplication' nameLabel="WritingCalculations_property_multiplication" type='string' />
            <property name='Equals' nameLabel="WritingCalculations_property_equals" type='string' />
        </property>
        <property displayName="Styles" name="Styles" nameLabel="WritingCalculations_property_styles" type="list">
            <property name="Column" nameLabel="WritingCalculations_property_column" type="string"/>
            <property name="Row" nameLabel="WritingCalculations_property_row" type="string"/>
            <property name="Class" nameLabel="WritingCalculations_property_class" type="string"/>
            <property name="Style" nameLabel="WritingCalculations_property_style" type="string"/>
        </property>
        <property displayName="Commutativity" name="Commutativity" nameLabel="WritingCalculations_property_commutativity" type="boolean" />
        <property displayName="Is not activity" name="Is not activity" nameLabel="WritingCalculations_property_is_not_activity" type="boolean"/>
        <property displayName="Enable more digits in gap" name="Multisigns" nameLabel="WritingCalculations_property_is_not_activity" type="boolean"/>
        <property displayName="Use numeric keyboard" name="useNumericKeyboard" nameLabel="WritingCalculations_use_numeric_keyboard" type="boolean" />
        <property name="showAllAnswersInGSA" nameLabel="WritingCalculations_show_all_answers_in_GSA" type="boolean" />
        <property name="DescriptionOfOperation" displayName="Description of operation" nameLabel="WritingCalculations_description_of_operation" type="string" />
        <property name="LangTag" displayName="Lang attribute" nameLabel="WritingCalculations_lang_attribute" type="string" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="WritingCalculations_speech_texts" type="staticlist">

            <property name="Gap" nameLabel="WritingCalculations_gap" type="staticrow">
                <property name="Gap" nameLabel="WritingCalculations_gap" type="string"/>
            </property>

            <property name="AdditionalGap" nameLabel="WritingCalculations_additional_gap" type="staticrow">
                <property name="AdditionalGap" nameLabel="WritingCalculations_additional_gap" type="string"/>
            </property>

            <property name="Empty" nameLabel="WritingCalculations_empty" type="staticrow">
                <property name="Empty" nameLabel="WritingCalculations_empty" type="string"/>
            </property>

            <property name="AdditionSign" nameLabel="WritingCalculations_addition_sign" type="staticrow">
                <property name="AdditionSign" nameLabel="WritingCalculations_addition_sign" type="string"/>
            </property>

            <property name="SubtractionSign" nameLabel="WritingCalculations_subtraction_sign" type="staticrow">
                <property name="SubtractionSign" nameLabel="WritingCalculations_subtraction_sign" type="string"/>
            </property>

            <property name="DivisionSign" nameLabel="WritingCalculations_division_sign" type="staticrow">
                <property name="DivisionSign" nameLabel="WritingCalculations_division_sign" type="string"/>
            </property>

            <property name="MultiplicationSign" nameLabel="WritingCalculations_multiplication_sign" type="staticrow">
                <property name="MultiplicationSign" nameLabel="WritingCalculations_multiplication_sign" type="string"/>
            </property>

            <property name="EqualsSign" nameLabel="WritingCalculations_equals_sign" type="staticrow">
                <property name="EqualsSign" nameLabel="WritingCalculations_equals_sign" type="string"/>
            </property>

            <property name="DecimalSeparator" nameLabel="WritingCalculations_decimal_separator" type="staticrow">
                <property name="DecimalSeparator" nameLabel="WritingCalculations_decimal_separator" type="string"/>
            </property>

            <property name="Line" nameLabel="WritingCalculations_line" type="staticrow">
                <property name="Line" nameLabel="WritingCalculations_line" type="string"/>
            </property>

            <property name="Correct" nameLabel="WritingCalculations_correct" type="staticrow">
                <property name="Correct" nameLabel="WritingCalculations_correct" type="string"/>
            </property>

            <property name="Wrong" nameLabel="WritingCalculations_wrong" type="staticrow">
                <property name="Wrong" nameLabel="WritingCalculations_wrong" type="string"/>
            </property>

        </property>
    </model>
</addon>

=== icplayer/icplayer/addons/Text_Coloring/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Text_Coloring' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="colors" displayName="Colors" type="list" nameLabel="Text_Coloring_property_colors">
			<property name="id" displayName="Color ID" nameLabel="Text_Coloring_property_color_id" type="string" />
			<property name="color" displayName="Color" nameLabel="Text_Coloring_property_color" type="string" />
			<property name="description" displayName="Description" nameLabel="Text_Coloring_property_description" type="string" isLocalized="true"/>
		</property>
		<property name="text" displayName="Text" nameLabel="Text_Coloring_property_text" type="text" isDefault="true" isLocalized="true"/>
		<property name="buttonsPosition" displayName="Buttons position" nameLabel="Text_Coloring_property_buttons_position" type="{left, top, bottom, right}" />
		<property name="hideColorsButtons" displayName="Hide Color Buttons" nameLabel="Text_Coloring_property_hide_color_buttons" type="boolean" />
		<property name="showSetEraserModeButton" displayName="Show set eraser mode button" nameLabel="Text_Coloring_property_show_set_eraser_mode_button" type="boolean" />
		<property name="eraserButtonText" displayName="Eraser button text" nameLabel="Text_Coloring_property_eraser_button_text" type="string" isLocalized="true" />
		<property name='Mode' nameLabel="Text_Selection_property_mode" type='{All selectable, Mark phrases to select}'/>
		<property name="countErrors" displayName="Count Errors" nameLabel="Text_Coloring_property_count_errors" type="boolean" />
	</model>
</addon>

=== icplayer/icplayer/addons/Slider/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Slider' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='ImageElement' nameLabel="Slider_property_image_element" type='image' />
		<property name="Orientation" nameLabel="Slider_property_orientation" type="{Landscape, Portrait}" />
		<property name="Stepwise" nameLabel="Slider_property_stepwise" type="boolean" />
		<property name="StepsCount" nameLabel="Slider_property_steps_count" type="string" />
		<property name="InitialStep" nameLabel="Slider_property_initial_step" type="string" />
		<property name="onStepChange" nameLabel="Slider_property_on_step_change" type="event" />
		<property name="Block in error checking mode" nameLabel="Slider_property_block_in_error_checking_mode" type="boolean" />
		<property name="Continuous events" nameLabel="Slider_property_continuous_events" type="boolean" />
        <property name="Continuous events steps" nameLabel="Slider_property_continuous_events_steps" type="{Stick, Smooth}" />
		<property name="Alternative texts" nameLabel="Slider_property_alternative_texts" type="list">
			<property name="Alternative text" nameLabel="Slider_property_alternative_text" type="text" />
			<property name="Step number" nameLabel="Slider_property_step_number" type="string" />
		</property>
		<property name="langAttribute" nameLabel="Slider_property_lang_attribute" type="string" />
		<property name="speechTexts" nameLabel="Slider_property_speech_texts" type="staticlist">
			<property name="Step" nameLabel="Slider_property_step" type="staticrow">
				<property name="Step" nameLabel="Slider_property_step" type="string"/>
			</property>
		</property>
	</model>
</addon>
