=== icplayer/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

    <xs:element name="addon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="model">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PropertyType">
        <xs:sequence>
            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="nameLabel" type="xs:string"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="isLocalized">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

</xs:schema>

=== icplayer/icplayer/addons/Animation/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Animation' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Preview image" nameLabel="Animation_property_preview_image" type="image" />
		<property name="Animation" nameLabel="Animation_property_animation" type="image" />
		<property name="Frames count" nameLabel="Animation_property_frames_count" type="string" />
		<property name="Frame duration" nameLabel="Animation_property_frame_duration" type="string" />
		<property name="Frame size" nameLabel="Animation_property_frame_size" type="{Original, Keep aspect ratio, Stretch}"/>
		<property name="Loop" nameLabel="Animation_property_loop" type="boolean" />
		<property name="Labels" nameLabel="Animation_property_labels" type="list">
			<property name="Text" nameLabel="Animation_property_text" type="string" isLocalized="true" />
			<property name="Top" nameLabel="Animation_property_top" type="string" />
			<property name="Left" nameLabel="Animation_property_left" type="string" />
			<property name="Frames" nameLabel="Animation_property_frames" type="string" />
		</property>
		<property name="Show watermark" nameLabel="Animation_property_show_watermark" type="boolean" />
		<property name="Watermark color" nameLabel="Animation_property_watermark_color" type="string" />
		<property name="Watermark opacity" nameLabel="Animation_property_watermark_opacity" type="string" />
		<property name="Watermark size" nameLabel="Animation_property_watermark_size" type="string" />
		<property name="Don't reset on end" nameLabel="Animation_property_do_not_reset_on_end" type="boolean" />
		<property name="Is click disabled" nameLabel="Animation_property_is_click_disabled" type="boolean" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="Animation_property_speech_texts" type="staticlist">
            <property name="Stop" nameLabel="Animation_property_stop_speech_text" type="staticrow">
                <property name="Stop" nameLabel="Animation_property_stop_speech_text" type="string"/>
            </property>
		</property>
		<property name="Alternative Text" displayName="Alternative Text" nameLabel="Animation_property_alt_text" type="text" />
		<property name="Preview Alternative Text" displayName="Preview Alternative Text" nameLabel="Animation_property_alt_text_prev" type="text" />
		<property name="langAttribute" displayName="Lang attribute" nameLabel="Animation_property_lang_attribute" type="string" />
	</model>
</addon>

=== icplayer/icplayer/addons/MathText/src/addon.xml
<?xml version="1.0" encoding="UTF-8" ?>

<addon id="MathText" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="initialText" nameLabel="Mathtext_property_text" type="mathtext" />
        <property name="correctAnswer" nameLabel="Mathtext_property_correctAnswer" type="mathanswer" />

        <property name="type" nameLabel="Mathtext_property_type" type="{text, editor, activity}" />
        <property name="isDisabled" nameLabel="Mathtext_property_is_disabled" type="boolean" />
        <property name="language" displayName="Language" nameLabel="Mathtext_property_language" type="{English, Polish, French, Arabic, Spanish}"/>

        <property name="formulaColor" type="string" nameLabel="Mathtext_property_formula_color" />
        <property name="backgroundColor" type="string" nameLabel="Mathtext_property_background_color" />

        <property name="mathEditorInPopup" nameLabel="Mathtext_property_math_editor_in_popup" type="boolean" />
        <property name="popupTexts" displayName="popup texts" nameLabel="Mathtext_property_popup" type="staticlist">

        <property name="cancel" nameLabel="Mathtext_property_popup_button_save" type="staticrow">
                <property name="cancel" nameLabel="Mathtext_property_popup_button_cancel" type="string"/>
        </property>
        <property name="save" nameLabel="Mathtext_property_popup_button_save" type="staticrow">
                <property name="save" nameLabel="Mathtext_property_popup_button_save" type="string"/>
        </property>

        </property>
    </model>
</addon>

=== icplayer/icplayer/addons/Line_Number/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Line_Number' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="Decimal Separator" nameLabel="Line_Number_property_decimal_separator" type="string" />
        <property name="Min" nameLabel="Line_Number_property_min" type="string" />
        <property name="Max" nameLabel="Line_Number_property_max" type="string" />
        <property name="Ranges" nameLabel="Line_Number_property_ranges" type="text" />
        <property name="Not Activity" nameLabel="Line_Number_property_not_activity" type="boolean" />
        <property name="Step" nameLabel="Line_Number_property_step" type="string" />
        <property name="Show Axis X Values" nameLabel="Line_Number_property_show_axis_x_values" type="boolean" />
        <property name="Axis X Values" nameLabel="Line_Number_property_axis_x_values" type="string" />
        <property name="Disable" nameLabel="Line_Number_property_disable" type="boolean" />
        <property name="Don't show ranges" nameLabel="Line_Number_property_dont_show_ranges" type="boolean" />
    </model>
</addon>

=== icplayer/icplayer/addons/Magic_Boxes/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Magic_Boxes' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name='Grid' nameLabel="Magic_Boxes_property_grid" type='text' isLocalized="true" />
        <property name='Answers' nameLabel="Magic_Boxes_property_answers" type='text' isLocalized="true" />
        <property name="CheckByWords" displayName="Check By Words" nameLabel="Magic_Boxes_property_check_by_words" type="boolean"/>
        <property name="langAttribute" displayName="Lang attribute" nameLabel="Magic_Boxes_property_lang_attribute" type="string" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="Magic_Boxes_property_speech_texts" type="staticlist">
            <property name="Cell" nameLabel="Magic_Boxes_property_speech_text_cell" type="staticrow">
                <property name="Cell" nameLabel="Magic_Boxes_property_speech_text_cell" type="string"/>
            </property>
            <property name="Selected" nameLabel="Magic_Boxes_property_speech_text_selected" type="staticrow">
                <property name="Selected" nameLabel="Magic_Boxes_property_speech_text_selected" type="string"/>
            </property>
            <property name="Deselected" nameLabel="Magic_Boxes_property_speech_text_deselected" type="staticrow">
                <property name="Deselected" nameLabel="Magic_Boxes_property_speech_text_deselected" type="string"/>
            </property>
            <property name="Correct" nameLabel="Magic_Boxes_property_speech_text_correct" type="staticrow">
                <property name="Correct" nameLabel="Magic_Boxes_property_speech_text_correct" type="string"/>
            </property>
            <property name="Wrong" nameLabel="Magic_Boxes_property_speech_text_wrong" type="staticrow">
                <property name="Wrong" nameLabel="Magic_Boxes_property_speech_text_wrong" type="string"/>
            </property>
        </property>
    </model>
</addon>

=== icplayer/icplayer/addons/MultiAudio/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='MultiAudio' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Files' nameLabel="MultiAudio_property_files" type='list' isDefault="true">
			<property name="ID" nameLabel="MultiAudio_property_id" type="string" />
			<property name="Mp3" nameLabel="MultiAudio_property_mp3" type="audio" />
			<property name="Ogg" nameLabel="MultiAudio_property_ogg" type="audio" />
			<property name="Enable loop" nameLabel="MultiAudio_property_enable_loop" type="boolean" />
			<property name="Text" nameLabel="MultiAudio_property_text" type="html" isLocalized="true" />
		</property>
		<property name="Interface" nameLabel="MultiAudio_property_interface" type="{None, Default controls, Display time, Draggable items}"/>
		<property name="Narration" nameLabel="MultiAudio_property_narration" type="narration" isLocalized="true"/>
		<property name="langAttribute" displayName="Lang attribute" nameLabel="MultiAudio_property_lang_attribute" type="string"/>
		<property name="speechTexts" displayName="Speech texts" nameLabel="MultiAudio_property_property_speech_texts" type="staticlist">

			<property name="Selected" nameLabel="MultiAudio_property_selected" type="staticrow">
				<property name="Selected" nameLabel="MultiAudio_property_selected" type="string"/>
			</property>

			<property name="Deselected" nameLabel="MultiAudio_property_deselected" type="staticrow">
				<property name="Deselected" nameLabel="MultiAudio_property_deselected" type="string"/>
			</property>

			<property name="Empty" nameLabel="MultiAudio_property_empty" type="staticrow">
				<property name="Empty" nameLabel="MultiAudio_property_empty" type="string"/>
			</property>

		</property>
	</model>
</addon>

=== icplayer/icplayer/addons/EditableWindow/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>
<addon id='EditableWindow' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="title" displayName="Title" nameLabel="EditableWindow_property_title" type="string"/>
        <property name="textEditor" nameLabel="EditableWindow_property_text_editor" type="html" />
        <property name="isTextEditorContent" nameLabel="EditableWindow_property_is_text_editor_content" type="boolean" />
        <property name="headerStyle" displayName="Header style" nameLabel="EditableWindow_property_header_style" type="string"/>
        <property name="fileList" displayName="File List" nameLabel="EditableWindow_property_file_list" type="list">
            <property name="id" displayName="ID" nameLabel="EditableWindow_property_id" type="string"/>
            <property name="file" displayName="File" nameLabel="EditableWindow_property_file" type="file"/>
        </property>
        <property name="index" displayName="Index File" nameLabel="EditableWindow_property_index_file" type="file"/>
        <property name="audio" displayName="Audio File" nameLabel="EditableWindow_property_audio_file" type="file"/>
        <property name="video" displayName="Video File" nameLabel="EditableWindow_property_video_file" type="file"/>
        <property name="editingEnabled" displayName="Editing enabled" nameLabel="EditableWindow_property_editing_enabled" type="boolean" />
        <property name="disableResizeHeight" displayName="Disable resize height" nameLabel="EditableWindow_property_disable_resize_height" type="boolean" />
        <property name="offlineMessage" nameLabel="EditableWindow_property_offline_message" type="text" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="EditableWindow_property_speech_texts" type="staticlist">
            <property name="openFullscreen" nameLabel="EditableWindow_property_openFullscreen" type="staticrow">
                <property name="openFullscreen" nameLabel="EditableWindow_property_openFullscreen" type="string"/>
            </property>
            <property name="closeFullscreen" nameLabel="EditableWindow_property_closeFullscreen" type="staticrow">
                <property name="closeFullscreen" nameLabel="EditableWindow_property_closeFullscreen" type="string"/>
            </property>
            <property name="closeWindow" nameLabel="EditableWindow_property_closeWindow" type="staticrow">
                <property name="closeWindow" nameLabel="EditableWindow_property_closeWindow" type="string"/>
            </property>
            <property name="textTool" nameLabel="EditableWindow_property_textTool" type="staticrow">
                <property name="textTool" nameLabel="EditableWindow_property_textTool" type="string"/>
            </property>
            <property name="highlightSelect" nameLabel="EditableWindow_property_highlightSelect" type="staticrow">
                <property name="highlightSelect" nameLabel="EditableWindow_property_highlightSelect" type="string"/>
            </property>
            <property name="pickAColor" nameLabel="EditableWindow_property_pickAColor" type="staticrow">
                <property name="pickAColor" nameLabel="EditableWindow_property_pickAColor" type="string"/>
            </property>
            <property name="yellow" nameLabel="EditableWindow_property_yellow" type="staticrow">
                <property name="yellow" nameLabel="EditableWindow_property_yellow" type="string"/>
            </property>
            <property name="blue" nameLabel="EditableWindow_property_blue" type="staticrow">
                <property name="blue" nameLabel="EditableWindow_property_blue" type="string"/>
            </property>
            <property name="red" nameLabel="EditableWindow_property_red" type="staticrow">
                <property name="red" nameLabel="EditableWindow_property_red" type="string"/>
            </property>
            <property name="green" nameLabel="EditableWindow_property_green" type="staticrow">
                <property name="green" nameLabel="EditableWindow_property_green" type="string"/>
            </property>
            <property name="white" nameLabel="EditableWindow_property_white" type="staticrow">
                <property name="white" nameLabel="EditableWindow_property_white" type="string"/>
            </property>
            <property name="noColor" nameLabel="EditableWindow_property_noColor" type="staticrow">
                <property name="noColor" nameLabel="EditableWindow_property_noColor" type="string"/>
            </property>
            <property name="reset" nameLabel="EditableWindow_property_reset" type="staticrow">
                <property name="reset" nameLabel="EditableWindow_property_reset" type="string"/>
            </property>
            <property name="image" nameLabel="EditableWindow_property_image" type="staticrow">
                <property name="image" nameLabel="EditableWindow_property_image" type="string"/>
            </property>
            <property name="audio" nameLabel="EditableWindow_property_audio" type="staticrow">
                <property name="audio" nameLabel="EditableWindow_property_audio" type="string"/>
            </property>
            <property name="video" nameLabel="EditableWindow_property_video" type="staticrow">
                <property name="video" nameLabel="EditableWindow_property_video" type="string"/>
            </property>
        </property>
        <property displayName="Lang attribute" name="langAttribute" nameLabel="EditableWindow_property_lang_attribute" type="string"/>
    </model>
</addon>

=== icplayer/icplayer/addons/graph/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='graph' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="isNotActivity" displayName="Is not an activity" nameLabel="graph_property_is_not_activity" type="boolean" />
		<property name="X axis description" nameLabel="graph_property_x_axis_description" type="string" isLocalized="true" />
		<property name="Show X axis bars descriptions" nameLabel="graph_property_show_x_axis_bars_descriptions" type="boolean" />
		<property name="X axis bars descriptions" nameLabel="graph_property_x_axis_bars_descriptions" type="list">
			<property name="Description" nameLabel="graph_property_description" type="string" isLocalized="true" />
		</property>
		<property name="Show X axis series descriptions" nameLabel="graph_property_show_x_axis_series_descriptions" type="boolean" />
		<property name="X axis series descriptions" nameLabel="graph_property_x_axis_series_descriptions" type="list">
			<property name="Description" nameLabel="graph_property_description" type="string" isLocalized="true" />
		</property>
		<property name="Y axis description" nameLabel="graph_property_y_axis_description" type="string" isLocalized="true" />
		<property name="Y axis maximum value" nameLabel="graph_property_y_axis_maximum_value" type="string" />
		<property name="Y axis minimum value" nameLabel="graph_property_y_axis_minimum_value" type="string" />
		<property name="Y axis grid step" nameLabel="graph_property_y_axis_grid_step" type="string" />
        <property name="Y axis values" nameLabel="graph_property_y_axis_values" type="string" />
		<property name="Interactive" nameLabel="graph_property_interactive" type="boolean" />
		<property name="Interactive step" nameLabel="graph_property_interactive_step" type="string" />
		<property name="Data" nameLabel="graph_property_data" type="text" />
		<property name="Answers" nameLabel="graph_property_answers" type="list">
			<property name="Answer" nameLabel="graph_property_answer" type="string" />
			<property name="Example" nameLabel="graph_property_is_example" type="boolean" />
		</property>
		<property name="Series colors" nameLabel="graph_property_series_colors" type="list">
			<property name="Color" nameLabel="graph_property_color" type="string" />
		</property>
		<property name="Decimal separator" nameLabel="graph_property_decimal_separator" type="string" />
	</model>
</addon>

=== icplayer/icplayer/addons/Count_and_Graph/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Count_and_Graph' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="isNotActivity" displayName="Is not an activity" nameLabel="Count_and_Graph_property_is_not_activity" type="boolean" />
        <property name="X axis description" nameLabel="Count_and_Graph_property_x_axis_description" type="string" isLocalized="true" />
        <property name="X axis data" nameLabel="Count_and_Graph_property_x_axis_data" type="list">
            <property name="Answer" nameLabel="Count_and_Graph_property_answer" type="string" />
            <property name="Color" nameLabel="Count_and_Graph_property_color" type="string" />
            <property name="Description" nameLabel="Count_and_Graph_property_description" type="string" isLocalized="true" />
            <property name="Description image" nameLabel="Count_and_Graph_property_description_image" type="image" />
            <property name="Example" nameLabel="Count_and_Graph_property_example" type="boolean" />
        </property>
        <property name="Y axis description" nameLabel="Count_and_Graph_property_y_axis_description" type="string" isLocalized="true" />
        <property name="Y axis maximum value" nameLabel="Count_and_Graph_property_y_axis_minimum_value" type="string" />
        <property name="Y axis values" nameLabel="Count_and_Graph_property_y_axis_values" type="string" />
        <property name="Bars width" nameLabel="Count_and_Graph_property_bars_width" type="string" />
        <property name="Background color" nameLabel="Count_and_Graph_property_background_color" type="string" />
        <property name="Grid line color" nameLabel="Count_and_Graph_property_grid_line_color" type="string" />
        <property name="Border" nameLabel="Count_and_Graph_property_border" type="string" />
    </model>
</addon>
