=== icplayer/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

    <xs:element name="addon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="model">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PropertyType">
        <xs:sequence>
            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="nameLabel" type="xs:string"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="isLocalized">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

</xs:schema>

=== icplayer/icplayer/addons/Text_Selection/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Text_Selection' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Mode' nameLabel="Text_Selection_property_mode" type='{Mark phrases to select, All selectable}'/>
		<property name='Selection type' nameLabel="Text_Selection_property_selection_type" type='{Single select, Multiselect}'/>
		<property name='Text' nameLabel="Text_Selection_property_text" type='html' isLocalized="true" isDefault="true"/>
        <property name='Enable letters selections' nameLabel="Text_Selection_property_enable_letters_selections" type='boolean'/>
        <property name="isNotActivity" displayName="Is Not Activity" nameLabel="Text_Selection_property_is_not_activity" type="boolean" />
		<property name="enableScroll" displayName="Enable scrolling on mobile" nameLabel="Text_Selection_property_enable_scroll" type="boolean" />
		<property name="langAttribute" displayName="Lang attribute" nameLabel="Text_Selection_property_lang_attribute" type="string" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="Text_Selection_property_speech_texts" type="staticlist">

            <property name="selectedSectionStart" nameLabel="Text_Selection_selected_section_start" type="staticrow">
                <property name="selectedSectionStart" nameLabel="Text_Selection_selected_section_start" type="string"/>
            </property>

			<property name="selectedSectionEnd" nameLabel="Text_Selection_selected_section_end" type="staticrow">
                <property name="selectedSectionEnd" nameLabel="Text_Selection_selected_section_end" type="string"/>
            </property>

			<property name="deselected" nameLabel="Text_Selection_deselected" type="staticrow">
                <property name="deselected" nameLabel="Text_Selection_deselected" type="string"/>
            </property>

			<property name="selected" nameLabel="Text_Selection_selected" type="staticrow">
                <property name="selected" nameLabel="Text_Selection_selected" type="string"/>
            </property>

			<property name="wrong" nameLabel="Text_Selection_wrong" type="staticrow">
                <property name="wrong" nameLabel="Text_Selection_wrong" type="string"/>
            </property>

			<property name="correct" nameLabel="Text_Selection_correct" type="staticrow">
                <property name="correct" nameLabel="Text_Selection_correct" type="string"/>
            </property>

            <property name="phrase" nameLabel="Text_Selection_phrase" type="staticrow">
                <property name="phrase" nameLabel="Text_Selection_phrase" type="string"/>
            </property>

			<property name="phraseEnd" nameLabel="Text_Selection_phrase_end" type="staticrow">
                <property name="phraseEnd" nameLabel="Text_Selection_phrase_end" type="string"/>
            </property>
		</property>
	</model>
</addon>

=== icplayer/icplayer/addons/Audio/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Audio' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="mp3" nameLabel="Audio_property_mp3" type="audio" />
		<property name="ogg" nameLabel="Audio_property_ogg" type="audio" />
		<property name="defaultControls" nameLabel="Audio_property_default_controls" type="boolean" />
        <property name="useBrowserControls" nameLabel="Audio_property_use_browser_controls" type="boolean" />
		<property name="displayTime" nameLabel="Audio_property_display_time" type="boolean" />
		<property name="enableLoop" nameLabel="Audio_property_enable_loop" type="boolean" />
		<property name="Narration" nameLabel="Audio_property_narration" type="narration" isLocalized="true" />
		<property name="onEnd" nameLabel="Audio_property_on_end" type="event"/>
		<property name="forceLoadAudio" nameLabel="Audio_property_force_load_audio" type="boolean"/>
		<property name="enablePlaybackSpeedControls" nameLabel="Audio_property_enable_playback_speed_controls" type="boolean"/>
	</model>
</addon>

=== icplayer/icplayer/addons/Connection/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Connection' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="isNotActivity" displayName="Is not an activity" nameLabel="Connection_property_is_not_activity" type="boolean" />
        <property name='Single connection mode' nameLabel="Connection_property_single_connection_mode" type='boolean'/>
        <property name="Left column" nameLabel="Connection_property_left_column" type="list" isDefault="true">
            <property name="id" nameLabel="Connection_property_id" type="string" />
            <property name="content" nameLabel="Connection_property_content" type="html" isLocalized="true" />
            <property name="connects to" nameLabel="Connection_property_connects_to" type="string" />
            <property name="additional class" nameLabel="Connection_property_additional_class" type="string" />
        </property>
        <property name="Right column" nameLabel="Connection_property_right_column" type="list">
            <property name="id" nameLabel="Connection_property_id" type="string" />
            <property name="content" nameLabel="Connection_property_content" type="html" isLocalized="true" />
            <property name="connects to" nameLabel="Connection_property_connects_to" type="string" />
            <property name="additional class" nameLabel="Connection_property_additional_class" type="string" />
        </property>
        <property name="Columns width" nameLabel="Connection_property_columns_width" type="list">
            <property name="left" nameLabel="Connection_property_left" type="string" />
            <property name="middle" nameLabel="Connection_property_middle" type="string" />
            <property name="right" nameLabel="Connection_property_right" type="string" />
        </property>
        <property name="initialConnections" nameLabel="Connection_property_initial_connection" type="list">
            <property name="from" nameLabel="Connection_property_initial_connection_from" type="string" />
            <property name="to" nameLabel="Connection_property_initial_connection_to" type="string" />
            <property name="isDisabled" nameLabel="Connection_property_initial_connection_is_disabled" type="boolean"/>
        </property>
        <property name="Default connection color" nameLabel="Connection_property_default_connection_color" type="string" />
        <property name="Correct connection color" nameLabel="Connection_property_correct_connection_color" type="string" />
        <property name="disabledConnectionColor" nameLabel="Connection_property_disabled_connection_color" type="string" />
        <property name="Incorrect connection color" nameLabel="Connection_property_incorrect_connection_color" type="string" />
        <property name="Connection thickness" nameLabel="Connection_property_connection_thickness" type="string" />
        <property name="Random order left column" nameLabel="Connection_property_random_order_left_column" type="boolean" />
        <property name="Random order right column" nameLabel="Connection_property_random_order_right_column" type="boolean" />
        <property name="Show answers line color" nameLabel="Connection_property_show_answers_line_color" type="string" />
        <property name="blockWrongAnswers" displayName="Block wrong answers" nameLabel="Connection_property_block_wrong_answers" type="boolean" />
        <property name="removeDraggedElement" displayName="Remove dragged element" nameLabel="Connection_property_remove_dragged_element" type="boolean" />

        <property name="langAttribute" displayName="Lang attribute" nameLabel="Connection_property_lang_attribute" type="string" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="Connection_property_speech_texts" type="staticlist">

            <property name="Connected" nameLabel="Connection_connected" type="staticrow">
                <property name="Connected" nameLabel="Connection_connected" type="string"/>
            </property>

            <property name="Disconnected" nameLabel="Connection_disconnected" type="staticrow">
                <property name="Disconnected" nameLabel="Connection_disconnected" type="string"/>
            </property>

            <property name="ConnectedTo" nameLabel="Connection_connected_to" type="staticrow">
                <property name="Connected to" nameLabel="Connection_connected_to" type="string"/>
            </property>

            <property name="Selected" nameLabel="Connection_selected" type="staticrow">
                <property name="Selected" nameLabel="Connection_selected" type="string"/>
            </property>

            <property name="Deselected" nameLabel="Connection_deselected" type="staticrow">
                <property name="Deselected" nameLabel="Connection_deselected" type="string"/>
            </property>

            <property name="Correct" nameLabel="Connection_correct" type="staticrow">
                <property name="Correct" nameLabel="Connection_correct" type="string"/>
            </property>

            <property name="Wrong" nameLabel="Connection_wrong" type="staticrow">
                <property name="Wrong" nameLabel="Connection_wrong" type="string"/>
            </property>
        </property>
    </model>
</addon>

=== icplayer/icplayer/addons/Navigation_Bar/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Navigation_Bar' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='ShowNextPrevArrows' type='boolean' displayName="Show Next and Prev arrows" nameLabel="Navigation_Bar_property_show_next_prev_arrows"/>
		<property name="HideHomeLastArrows" type="boolean" displayName="Hide Home and Last arrows" nameLabel="Navigation_Bar_property_show_home_last_arrows"/>
		<property name="Numericals" type="{Western Arabic,Eastern Arabic,Perso-Arabic}" nameLabel="Navigation_Bar_property_numericals"/>
        <property displayName="Styles" name="Styles" type="list" nameLabel="Navigation_Bar_property_styles">
            <property name="Pages" type="string" nameLabel="Navigation_Bar_property_pages"/>
            <property name="Class" type="string" nameLabel="Navigation_Bar_property_class"/>
            <property name="Style" type="string" nameLabel="Navigation_Bar_property_style"/>
        </property>
        <property name='AddClassNBPageOK' type='boolean' displayName='Real-time navigationbar-page-ok' nameLabel="Navigation_Bar_property_add_class_nb_page_ok"/>
        <property name='firstPageAsCover' type='boolean' displayName='First page as cover' nameLabel="Navigation_Bar_property_first_page_as_cover"/>
        <property name='lastPageSeparated' type='boolean' displayName='Last page separated' nameLabel="Navigation_Bar_property_last_page_separated"/>
        <property name="speechTexts" displayName="Speech texts" nameLabel="Navigation_Bar_property_speech_texts" type="staticlist">
            <property name="GoToPageNumber" nameLabel="Navigation_Bar_property_go_to_page_number" type="staticrow">
                <property name="GoToPageNumber" nameLabel="Navigation_Bar_property_go_to_page_number" type="string"/>
            </property>
            <property name="NextPage" nameLabel="Navigation_Bar_property_go_to_next_page" type="staticrow">
                <property name="NextPage" nameLabel="Navigation_Bar_property_go_to_next_page" type="string"/>
            </property>
            <property name="PrevPage" nameLabel="Navigation_Bar_property_go_to_prev_page" type="staticrow">
                <property name="PrevPage" nameLabel="Navigation_Bar_property_go_to_prev_page" type="string"/>
            </property>
            <property name="Titled" nameLabel="Navigation_Bar_property_titled" type="staticrow">
                <property name="Titled" nameLabel="Navigation_Bar_property_titled" type="string"/>
            </property>
            <property name="DottedRight" nameLabel="Navigation_Bar_property_show_more" type="staticrow">
                <property name="DottedRight" nameLabel="Navigation_Bar_property_show_more" type="string"/>
            </property>
            <property name="DottedLeft" nameLabel="Navigation_Bar_property_show_prev" type="staticrow">
                <property name="DottedLeft" nameLabel="Navigation_Bar_property_show_prev" type="string"/>
            </property>
            <property name="DisabledPage" nameLabel="Navigation_Bar_property_disabled_page" type="staticrow">
                <property name="DisabledPage" nameLabel="Navigation_Bar_property_disabled_page" type="string"/>
            </property>
        </property>
        <property name="langAttribute" displayName="Lang attribute" nameLabel="Navigation_Bar_property_lang_attribute" type="string" />
        <property name='playTitle' type='boolean' nameLabel="Navigation_Bar_property_play_title"/>
        <property name='blockNotVisited' type='boolean' displayName='Block not visited pages' nameLabel="Navigation_Bar_property_block_not_visited"/>
	</model>
</addon>

=== icplayer/icplayer/addons/Text_To_Speech/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>
<addon id='Text_To_Speech' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="configuration" displayName="Configuration" nameLabel="Text_To_Speech_configuration" type="list" isDefault="true">
            <property name="ID" nameLabel="Text_To_Speech_property_id" type="string" />
            <property name="Area" displayName="Area" nameLabel="Text_To_Speech_area" type="{Main, Header, Footer}" />
            <property name="Title" nameLabel="Text_To_Speech_property_title" type="string" isLocalized="true" />
        </property>

        <property name="EnterText" nameLabel="Text_To_Speech_property_enter_text" type="string" isLocalized="true" />
        <property name="ExitText" nameLabel="Text_To_Speech_property_exit_text" type="string" isLocalized="true" />
        <property name="NewPage" nameLabel="Text_To_Speech_property_new_page" type="string" isLocalized="true" />
        <property name="PageLangTag" nameLabel="Text_To_Speech_property_page_lang_tag" type="string" isLocalized="true" />
        <property name="disableNewPageMessage" nameLabel="Text_To_Speech_property_disable_new_page_message" type="boolean"/>
    </model>
</addon>

=== icplayer/icplayer/addons/Board_Game/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="Board_Game" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="Background" displayName="Background" nameLabel="Board_game_property_background" type="image"/>
        <property name="hasFields" displayName="has Fields" nameLabel="Board_game_property_has_fields" type="boolean"/>
        <property name="Fields" nameLabel="Board_game_property_fields" type="list" isDefault="true">
            <property name="Top" nameLabel="Board_game_property_top" type="string"/>
            <property name="Left" nameLabel="Board_game_property_left" type="string"/>
            <property name="Width" nameLabel="Board_game_property_width" type="string"/>
            <property name="Height" nameLabel="Board_game_property_height" type="string"/>
            <property name="cssClass" nameLabel="Board_game_property_css_class" type="string"/>
        </property>
        <property name="Images" displayName="Elements" nameLabel="Board_game_property_images" type="list">
            <property name="PawnImage" displayName="Element Image" nameLabel="Board_game_property_pawn_image" type="image"/>
            <property name="Top" nameLabel="Board_game_property_top" type="string"/>
            <property name="Left" nameLabel="Board_game_property_left" type="string"/>
            <property name="Width" nameLabel="Board_game_property_width" type="string"/>
            <property name="Height" nameLabel="Board_game_property_height" type="string"/>
        </property>
        <property name="isDisabled" nameLabel="Board_game_property_is_disable" type="boolean"/>
        <property name="gameMode" nameLabel="Board_game_property_game_mode" type="{Free,Game}"/>
	</model>
</addon>

=== icplayer/icplayer/addons/Fractions/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="Fractions" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Figure" nameLabel="Fractions_property_figure" type="{---,Rectangular,Circle,Square}"/>
		<property name="RectHorizontal" displayName="Rectangular horizontal parts" nameLabel="Fractions_property_rect_horizontal" type="string" />
		<property name="RectVertical" displayName="Rectangular vertical parts" nameLabel="Fractions_property_rect_vertical" type="string" />
		<property name="CircleParts" displayName="Circle parts" type="string" nameLabel="Fractions_property_circle_parts"/>
		<property name="SquareParts" displayName="Square parts" type="string" nameLabel="Fractions_property_square_parts"/>
		<property name="Correct" displayName="Number of correct parts" nameLabel="Fractions_property_correct" type="string" />
		<property name="selectedParts" displayName="Selected parts" nameLabel="Fractions_property_selected_parts" type="string" />
		<property name="selectionColor" displayName="Selection color" nameLabel="Fractions_property_selection_color" type="string" />
		<property name="emptyColor" displayName="Empty color" nameLabel="Fractions_property_empty_color" type="string" />
		<property name="strokeColor" displayName="Stroke color" nameLabel="Fractions_property_stroke_color" type="string" />
		<property name="strokeWidth" displayName="Stroke width" nameLabel="Fractions_property_stroke_width" type="string" />
		<property name="isNotActivity" nameLabel="Fractions_property_is_not_activity" type="boolean"/>
		<property name="isDisable" nameLabel="Fractions_property_is_disable" type="boolean"/>
        <property name="imageDeselect" displayName="Image for deselected parts" nameLabel="Fractions_property_is_deselect" type="image"/>
        <property name="imageSelect" displayName="Image for selected parts" nameLabel="Fractions_property_is_select" type="image"/>
		<property name="speechTexts" displayName="Speech texts" nameLabel="Fractions_property_speech_texts"
				  type="staticlist">
			<property name="Selected" nameLabel="Fractions_speech_text_selected" type="staticrow">
				<property name="Selected" nameLabel="Fractions_speech_text_selected" type="string"/>
			</property>
			<property name="Deselected" nameLabel="Fractions_speech_text_deselected" type="staticrow">
				<property name="Deselected" nameLabel="Fractions_speech_text_deselected" type="string"/>
			</property>
			<property name="Item" nameLabel="Fractions_speech_text_item" type="staticrow">
				<property name="Item" nameLabel="Fractions_speech_text_item" type="string"/>
			</property>
			<property name="Correct" nameLabel="Fractions_speech_text_correct" type="staticrow">
				<property name="Correct" nameLabel="Fractions_speech_text_correct" type="string"/>
			</property>
			<property name="Wrong" nameLabel="Fractions_speech_text_wrong" type="staticrow">
				<property name="Wrong" nameLabel="Fractions_speech_text_wrong" type="string"/>
			</property>
			<property name="of" nameLabel="Fractions_speech_text_of" type="staticrow">
				<property name="of" nameLabel="Fractions_speech_text_of" type="string"/>
			</property>
		</property>
	</model>
</addon>

=== icplayer/icplayer/addons/Zoom_Image/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id="Zoom_Image" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="Full Screen image" displayName="Full Screen image" nameLabel="Zoom_Image_property_full_screen_image" type="image" />
        <property name="Page image" displayName="Page image" nameLabel="Zoom_Image_property_page_image" type="image" />
        <property name="Alternative text" nameLabel="Zoom_Image_property_alternative_text" type="string" />
        <property name="langAttribute" displayName="Lang attribute" nameLabel="Zoom_image_property_lang_attribute" type="string" />
         <property name="speechTexts" displayName="Speech texts" nameLabel="Zoom_image_property_speech_texts" type="staticlist">
            <property name="Closed" nameLabel="Zoom_image_property_closed" type="staticrow">
                <property name="Closed" nameLabel="Zoom_image_property_closed" type="string"/>
            </property>
        </property>
    </model>
</addon>
